os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- openssl aes-256-cbc -K $encrypted_8e77b177e614_key -iv $encrypted_8e77b177e614_iv
  -in core/src/test/resources/xatkit-secrets.tar.enc -out core/src/test/resources/xatkit-secrets.tar
  -d
- tar xvf core/src/test/resources/xatkit-secrets.tar -C core/src/test/resources
script:
- mvn -B jacoco:prepare-agent test jacoco:report jacoco:report-aggregate
after_success:
- bash <(curl -s https://codecov.io/bash) -t $CODECOV_UPLOAD_TOKEN
- bash .util/publish_javadoc.sh
notifications:
  slack:
    secure: nLd9z5M4QqIxdD6bR/8UDbmkQLxu6fzoyN3TQU8UXvrSGFRsgZHNjcPNfHigEP8S9vP6K8oCkedvLV20+2vci9k/x2DtxuYjH1gF9yZpQfIVubvVDe353/swBwWeDFu0+5KLvS9ExjN9LUj09CwC9/MWEXx1436fAXyXr8z+kIAr/u1Fu+bGvsQlkCLvt6YfUExFN3fZvXFR0O5gLRdW0o42Yn23nmxgL5y7ZsjexZyqa95yI45ks7276i9V43L6IthU66FsWzG6Imyp6plTFkBMPFdbWtnUl37GP/58ROQtilRMJzcB2/90MrAyz8bmOCuGPCCviZTcwgNsd9pBShUnNKPclVvHgzBXxyelSw3Ls+v3LNZ13SKujiralO9BnWn2rIgxccdVj+PJGi0lvAB3g+P7ESenojaII9HublCHK80NpbF4BJuR1RPRmoO3ni4inoN6jCxinSS7EtwWOa/8oc1BOB9963ThTZhyVik+ezDz3ArcQmzLeFtLIKG+OVCFyjxuJzKRGQ1X6WyqUwbhIKn5WYBpUccpBocWYIxt0cHBOLnKqwXwRloARZ9oXqyLxS/QM6w2idwdZ4HByc7KzoQjEwmR58Nz17quk/1Vwpl9qf5ie+/qbCh+0OTjetMPnpGoUOC90Yjuen5hS0n+466WixV4nb1t7XE0tPo=
